### ISSUE TITLE
Extend Intervention Costings Loading

### ISSUE THREAD

**Issue by andy-bevan** [micronutrientsupport/database-architecture#314] opened 2022-03-15 12:02 UTC
At present we are only importing large scale fortification models for wheat flour and maize flour. 

We also need to import data from the existing excel file for biofortification, such as VA maize and OFSP.

And also agro-fortification such as maize agronomic Zn.

We can then extend the database processing of the data for API end points and onwards.

**Comment by rbroth** [comment] 2023-02-08 09:56
duplicate of #259

**Closed by rbroth** 2023-02-08 09:56 UTC
